version: "3"

services:
  auction-web:
    restart: always
    image: nginx:alpine
    container_name: auction-web
    volumes:
      - ./dist:/usr/src/app/dist
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8012:80
